const FETCH_GAMES = 'FETCH_GAMES';
const GAME_DETAIL = 'GAME_DETAIL';
const UPLOAD_GENRES = 'UPLOAD_GENRES';
const ADD_GAME = 'ADD_GAME'
const UPDATE_PAGES = 'UPDATE_PAGES';
const SEARCH_GAMES = 'SEARCH_GAMES';
const FILTER_BY_GENRE = 'FILTER_BY_GENRE';
const SHOW_ALL = 'SHOW_ALL'
const UPDATE_ORDER_PARAMS = 'UPDATE_ORDER_PARAMS'
const JUMP_PAGE = 'JUMP_PAGE'
const UPDATE_SEARCH_KEY = 'UPDATE_SEARCH_KEY'
const UPDATE_GENRE_SELECTED = 'UPDATE_GENRE_SELECTED'

export { FETCH_GAMES, GAME_DETAIL, UPLOAD_GENRES, ADD_GAME, UPDATE_PAGES, SEARCH_GAMES, FILTER_BY_GENRE, SHOW_ALL, UPDATE_ORDER_PARAMS, JUMP_PAGE, UPDATE_SEARCH_KEY, UPDATE_GENRE_SELECTED };